name: Deploy to Linode Compute Instance

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: php-actions/composer@v6
    # - uses: php-actions/phpunit@v3

    - name: Build Dependencies
      run: composer update

    - name: Run Tests
      run: ./test.sh

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aos-tracker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull and Run Docker Image on Linode Remote Server
        uses: appleboy/ssh-action@master
        env:
          HOST_PORT: ${{ secrets.HOST_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }} 
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: HOST_PORT,DB_HOST,DB_USER,DB_PASS
          script: |
            export envArray=( "$HOST_PORT" "$DB_HOST" "$DB_USER" "$DB_PASS" ) \
            && docker pull thoughtspring/aos-tracker \
            && if [[ -z $(docker container ls -a | grep "aos-tracker") ]]; \
            then echo "No container found. Starting aos-tracker container..."; \
            else docker stop aos-tracker && docker rm aos-tracker; \
            fi \
            && docker run -d -p "${envArray[0]}":80 --name aos-tracker --restart always \
            -e DB_HOST="${envArray[1]}" \
            -e DB_USER="${envArray[2]}" \
            -e DB_PASS="${envArray[3]}" \
            thoughtspring/aos-tracker \
            && exit \
            && exit 0;